version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
    container_name: cosmotrade
    restart: always
    depends_on:
      - redis
    expose:
      - "5000"
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      CHAT_ID: ${CHAT_ID}
      EXCHANGE: ${EXCHANGE}
      WTF_SECRET_KEY: ${WTF_SECRET_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - /etc/letsencrypt/live/yourdomain.com/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
    - /etc/letsencrypt/live/yourdomain.com/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - app
