version: "3.8"

services:
  app:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: ["python3", "main.py"]

  redis:
    image: redis:7
    ports:
      - "6379:6379"
